services:
  app:
    build: .
    container_name: budgetflow-app
    restart: always
    ports:
      - "127.0.0.1:8095:8095"
    environment:
      - NODE_ENV=production
      - PORT=8095
    env_file:
      - .env.local.prod
    #volumes:
    #  - .:/app
    #  - /app/node_modules