FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

# ── Build-time variables (NEXT_PUBLIC_* are inlined at build) ──
# Pass via: docker build --build-arg NEXT_PUBLIC_FIREBASE_API_KEY=...
# or via docker-compose build args.

ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY

ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}

# Les secrets privés (FIREBASE_PRIVATE_KEY, CRON_SECRET, etc.) sont
# injectés au runtime via docker-compose env_file — ils ne sont PAS
# inclus dans l'image Docker.

COPY . .

RUN npm run build

EXPOSE 8095

# Override host to 0.0.0.0 inside the container so Docker's port mapping
# can reach the server. The docker-compose binds only to 127.0.0.1 on
# the host, so the service is not exposed to the external network.
CMD ["npx", "next", "start", "-p", "8095", "-H", "0.0.0.0"]